name: publish-nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish-library:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - uses: NuGet/setup-nuget@v1.0.2 
            
    - name: Build library
      working-directory: ./src/Vrasoft.DebugSignatures
      run: dotnet build -c Release
    
    - name: Save NuGet packages
      uses: actions/upload-artifact@v2
      with:
        name: built-nuget-packages
        path: src/Vrasoft.DebugSignatures/bin/Release/*nupkg
      
    - name: Publish NuGet packages
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 
      run: |
        # nuget source list
        # nuget setApiKey "$NUGET_API_KEY" -source https://api.nuget.org/v3/index.json
        nuget setApiKey "$NUGET_API_KEY"
        nuget push $(find -name '*.nupkg') -ApiKey "$NUGET_API_KEY"
 

