name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
          
    - name: Build library
      working-directory: ./src/Vrasoft.DebugSignatures
      run: dotnet build -c Release
    
    - name: Save NuGet package
      uses: actions/upload-artifact@v2
      with:
          path: src/Vrasoft.DebugSignatures/bin/Release/*.nupkg
      
    - name: Save NuGet symbols package
      uses: actions/upload-artifact@v2
      with:
          path: src/Vrasoft.DebugSignatures/bin/Release/*.snupkg
                  
 

