name: publish-build

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish-library:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
            
    - name: Build library
      working-directory: ./src/Vrasoft.DebugSignatures
      run: dotnet build -c Release
    
    - name: Save NuGet packages
      uses: actions/upload-artifact@v2
      with:
        name: built-nuget-packages
        path: src/Vrasoft.DebugSignatures/bin/Release/*nupkg
      
    - name: Publish NuGet packages
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 
      run: |
        dotnet nuget push $(find -name '*.nupkg') -s https://api.nuget.org/v3/index.json -k "$NUGET_API_KEY" --skip-duplicate --no-symbols
        dotnet nuget push $(find -name '*.snupkg') -s https://api.nuget.org/v3/index.json -k "$NUGET_API_KEY" --skip-duplicate
      
  build-cli-and-gui:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      
    - name: Download built NuGet packages
      uses: actions/download-artifact@v2
      with:
        name: built-nuget-packages
        path: local_nuget
      
    - name: Set local NuGet repository
      run: |
        cd local_nuget
        dotnet nuget add source . -n local_nuget
        
    - name: Build CLI
      run: dotnet build ./src/Vrasoft.DebugSignatures.ComparerCli -c Release -o Build
      
    - name: Build GUI
      run: dotnet build ./src/Vrasoft.DebugSignatures.ComparerGui -c Release -o Build
      
    - name: Save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: debug-signatures-comparer-app
        path: ./Build

