name: publish-build

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish-library:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
            
    - name: Build library
      working-directory: ./src/Signet
      run: dotnet build -c Release
    
    - name: Save NuGet packages
      uses: actions/upload-artifact@v2
      with:
        name: built-nuget-packages
        path: src/Signet/bin/Release/*nupkg
      
    - name: Publish NuGet packages
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        if $(dotnet nuget push $(find -name '*.nupkg') -s https://api.nuget.org/v3/index.json -k "$NUGET_API_KEY" --skip-duplicate --no-symbols true) | grep "Created"; then
          dotnet nuget push $(find -name '*.snupkg') -s https://api.nuget.org/v3/index.json -k "$NUGET_API_KEY"
        fi
        
  build-cli-and-gui:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
      
    - name: Build self-contained
      run: |
        dotnet publish ./src/Signet.ComparerGui -c Release -o build/win-x64 --self-contained=false -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish ./src/Signet.ComparerCli -c Release -o build/win-x64 --self-contained=false -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish ./src/Signet.ComparerCli -c Release -o build/linux-x64 --self-contained=false -r linux-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish ./src/Signet.ComparerCli -c Release -o build/osx-x64 --self-contained=true -r osx-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
        
    - name: Save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build
      

